version: '3.8'
services:
#  frontend:
#    container_name: frontend
#    build: ./frontend
#    ports:
#      - "4200:4200"
#    working_dir: /usr/src/app
#    volumes:
#      - type: bind
#        source: ./frontend
#        target: /usr/src/app
#      - /app/usr/src/node_modules

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    container_name: backend
    working_dir: /usr/src/app
#    links:
#      - database
#    depends_on:
#      - database
#    volumes:
#      - ./backend:/usr/src/app
#      - /usr/src/app/node_modules
##      - ./:/app
##      - /usr/src/app/node_modules
##      - type: bind
##        source: ./backend
##        target: /usr/src/app
#
#  database:
#    image: postgres:13-alpine3.18
#    container_name: database
#    restart: always
#    ports:
#      - "5432:5432"
#    environment:
#      - POSTGRES_USER=${POSTGRES_USER}
#      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
#      - POSTGRES_DB=${POSTGRES_DB}
#    volumes:
#      - postgres-db:${POSTGRES_DATA_DIR}
#
#volumes:
#  postgres-db: