version: "3.8"
services:
  # NestJS Api
  api:
    build:
      dockerfile: Dockerfile
      context: ./api
      target: development
    volumes:
      - ./api:/usr/src/app/api
      - /usr/src/app/api/node_modules
#    command: npm run start:dev
    depends_on:
      - database
    environment:
      DATABASE_URL: "postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:${POSTGRES_PORT}/db"
      NODE_ENV: development
    ports:
      - "3000:3000"

  # React
  web:
    build:
      dockerfile: Dockerfile
      context: ./web
      target: development
    volumes:
      - ./web:/usr/src/app/web
      - /usr/src/app/web/node_modules
    ports:
      - "8000:8000"
    links:
      - api
    tty: true

  # Postgres Database for NestJS to connect to
  database:
    image: postgres:13-alpine3.18
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - postgres-db:${POSTGRES_DATA_DIR}

volumes:
  postgres-db: